[package]
name = "xusdc-genesis"
version.workspace      = true
edition.workspace = true
publish = false
description = "Builds the genesis USDCx faucet"

[dependencies]
miden-protocol = { workspace = true, features = ["testing"] }
miden-standards = { workspace = true }
miden-objects = { workspace = true }
xusdc-encoding = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
rstest = { workspace = true }
tempfile = { workspace = true }
