[[fungible_faucet]]
account_type = "public"
decimals     = 3
max_supply   = 100_000_000
symbol       = "WHAT"

[[wallet]]
account_type = "private"
assets       = [{ amount = 999_000, symbol = "USDCX" }]
name         = "wallet_treasury"

[[wallet]]
account_type = "private"
assets       = [{ amount = 777, symbol = "USDCX" }]
name         = "wallet_user"

[[wallet]]
account_type = "private"
assets       = [{ amount = 1, symbol = "WHAT" }]
name         = "wallet_what"
