#!/bin/bash
#
# This is a postinstallation script so the service can be configured and started when requested.

# User is expected by the systemd service file
sudo adduser --disabled-password --disabled-login --shell /usr/sbin/nologin --quiet --system --no-create-home --home /nonexistent miden-prover

sudo systemctl daemon-reload
sudo systemctl enable miden-prover
sudo systemctl start miden-prover
