services:
  monitor:
    image: miden-network-monitor
    pull_policy: if_not_present
    depends_on:
      sequencer:
        condition: service_started
    command:
      - miden-network-monitor
      - start
    environment:
      - MIDEN_MONITOR_RPC_URL=http://sequencer:57291
      - MIDEN_MONITOR_PORT=3001
      - MIDEN_MONITOR_NETWORK_NAME=Localhost
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
    ports:
      - "3001:3001"
