services:
  prometheus:
    image: prom/prometheus:v2.55.1
    volumes:
      - ./compose/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=exemplar-storage"
    ports:
      - "9090:9090"

volumes:
  prometheus-data:
