
name: "Install protobuf compiler"
description: "Install compiler for protobuf compilation"

runs:
  using: "composite"
  steps:
    - name: Install protobuf compiler
      shell: bash
      run: |
        set -eux
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
