#!/bin/bash
#
###############
# Remove miden-node installs
##############
for svc in miden-node miden-validator; do
    sudo rm -rf "/lib/systemd/system/$svc.service"
    sudo rm -rf "/etc/opt/$svc"
    sudo deluser "$svc"
done

sudo systemctl daemon-reload
