# Checks that run once per day.
#
# These are generally expensive jobs that don't provide enough utility to run on _every_ PR.
name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # Everyday at 06:00am UTC

permissions:
  contents: read

jobs:
  # Run tests on the beta channel to provide feedback for Rust team.
  beta-test:
    name: test on beta channel
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: "next"
          persist-credentials: false
      - name: Cleanup large tools for build space
        uses: ./.github/actions/cleanup-runner
      - uses: ./.github/actions/install-rocksdb
      - uses: ./.github/actions/install-protobuf-compiler
      - name: Rustup
        run: rustup install beta && rustup default beta
      - uses: taiki-e/install-action@055f5df8c3f65ea01cd41e9dc855becd88953486 # v2.75.18
        with:
          tool: nextest@0.9.122
      - name: Run tests
        run: make test

  # Check all feature combinations work individually.
  #
  # This check is too expensive to run on every PR, both in terms of CPU and cache size.
  check-features:
    name: feature combinations
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: "next"
          persist-credentials: false
      - name: Cleanup large tools for build space
        uses: ./.github/actions/cleanup-runner
      - uses: ./.github/actions/install-rocksdb
      - uses: ./.github/actions/install-protobuf-compiler
      - name: Install rust
        run: rustup toolchain install --no-self-update
      - name: Install cargo-hack
        uses: taiki-e/install-action@055f5df8c3f65ea01cd41e9dc855becd88953486 # v2.75.18
        with:
          tool: cargo-hack
      - name: Check all feature combinations
        run: make check-features
