name: Publish Docker Images

on:
  release:
    types: [prereleased, released]

  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (E.G. v0.10.0-rc.1, v0.10.0). Corresponding git tag must already exist."
        required: true
        type: string

env:
  version: ${{ inputs.version || github.ref_name }}
  registry: ghcr.io
  DOCKER_PLATFORMS: linux/amd64,linux/arm64

permissions:
  id-token: write
  contents: write
  packages: write
  attestations: write

jobs:
  publish:
    runs-on: warp-ubuntu-latest-x64-8x
    environment: publish-docker
    strategy:
      matrix:
        include:
          - component: node
            bin: miden-node
            port: 57291
          - component: validator
            bin: miden-validator
            port: 50101
          - component: ntx-builder
            bin: miden-ntx-builder
            port: 50301
          - component: remote-prover
            bin: miden-remote-prover
            port: 50051
          - component: network-monitor
            bin: miden-network-monitor
            port: 3000
    name: Publish ${{ matrix.component }} ${{ inputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ env.version }}
          fetch-depth: 0
          persist-credentials: false

      - name: Prepare image metadata
        id: metadata
        run: |
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"
          echo "commit=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Log in to the Container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: WarpBuilds/build-push-action@ec038a9f4b87a7c7ccb50ac7a26a90d46a610a81 # v6.0.9
        with:
          context: .
          push: true
          file: ./Dockerfile
          platforms: ${{ env.DOCKER_PLATFORMS }}
          profile-name: ${{ vars.WARPBUILD_DOCKER_BUILDER_PROFILE }}
          pull: true
          build-args: |
            BIN=${{ matrix.bin }}
            PORT=${{ matrix.port }}
            CREATED=${{ steps.metadata.outputs.created }}
            VERSION=${{ env.version }}
            COMMIT=${{ steps.metadata.outputs.commit }}
          tags: ${{ env.registry }}/0xmiden/miden-${{ matrix.component }}:${{ env.version }}
